[build]
  functions = "netlify/functions"
  command = "pip install -r netlify/functions/requirements.txt && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.8"

# Schedule the token refresh every hour
[[plugins]]
  package = "@netlify/plugin-scheduled-functions"
  [plugins.inputs]
    hourly = ["getSpotifyToken"]
