[build]
  functions = "netlify/functions"
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.js", "**/*.mjs"]
  node_env = { ESBUILD_FORCE_KEEP_IMPORT_META = "true" }