[build]
  functions = "netlify/functions"
  command = "pip install -r netlify/functions/requirements.txt && npm run build; python --version; python3 --version; echo$PATH"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  included_files = ["**/*.js", "**/*.mjs"]
  node_env = { ESBUILD_FORCE_KEEP_IMPORT_META = "true" }
  

[build.environment]
  PYTHON_VERSION = "3.8"