[build]
  functions = "netlify/functions"
  command = "npm run predev && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"

[build.environment]
  PYTHON_VERSION = "3.8"

[[plugins]]
  package = "netlify-plugin-python"
  [plugins.inputs]
    packages = ["requests", "python-dotenv"]